package Management;

import javax.swing.*;
import java.awt.*;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author DELL
 */
public class ManagementMenu extends JFrame {

    /**
     * Creates new form Menu
     */
    public ManagementMenu () {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel2 = new JLabel();
        jButton1 = new JButton();
        jButton2 = new JButton();
        jButton3 = new JButton();
        jButton4 = new JButton();
        jButton5 = new JButton();
        jButton6 = new JButton();
        jButton7 = new JButton();
        jButton8 = new JButton();
        jLabel1 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        jLabel9 = new JLabel();
        jLabel10 = new JLabel();

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setTitle("CoffeeShop");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new Color(255, 255, 255));
        jLabel2.setFont(new Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setText("        MANAGEMENT MENU");
        jLabel2.setVerticalAlignment(SwingConstants.TOP);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 47, 550, -1));

        jButton1.setBackground(new Color(162, 93, 36));
        jButton1.setForeground(new Color(162, 93, 36));
        jButton1.setIcon(new ImageIcon(getClass().getResource("/mycofffee2/tea-plant-leaf-icon.png"))); // NOI18N
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 109, 81, 60));

        jButton2.setBackground(new Color(162, 93, 36));
        jButton2.setIcon(new ImageIcon(getClass().getResource("/mycofffee2/drink-4-icon.png"))); // NOI18N
        jButton2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 109, 73, 60));

        jButton3.setBackground(new Color(162, 93, 36));
        jButton3.setIcon(new ImageIcon(getClass().getResource("/mycofffee2/32410-fish-cake-with-swirl-icon.png"))); // NOI18N
        jButton3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 109, 73, 60));

        jButton4.setBackground(new Color(162, 93, 36));
        jButton4.setIcon(new ImageIcon(getClass().getResource("/mycofffee2/Ecommerce-Bill-icon.png"))); // NOI18N
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 228, -1, 65));

        jButton5.setBackground(new Color(162, 93, 36));
        jButton5.setIcon(new ImageIcon(getClass().getResource("/mycofffee2/Places-user-identity-icon.png"))); // NOI18N
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 228, 73, 65));

        jButton6.setBackground(new Color(162, 93, 36));
        jButton6.setIcon(new ImageIcon(getClass().getResource("/mycofffee2/preferences-desktop-online-accounts-icon.png"))); // NOI18N
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 228, 73, 65));

        jButton7.setBackground(new Color(162, 93, 36));
        jButton7.setIcon(new ImageIcon(getClass().getResource("/mycofffee2/dollar-stats-icon.png"))); // NOI18N
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 369, 81, -1));

        jButton8.setBackground(new Color(162, 93, 36));
        jButton8.setIcon(new ImageIcon(getClass().getResource("/mycofffee2/system-log-out-icon.png"))); // NOI18N
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 369, 73, -1));

        jLabel1.setFont(new Font("Arial Black", 1, 12)); // NOI18N
        jLabel1.setText("   Classify");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 180, 97, -1));

        jLabel3.setFont(new Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setText("  Product");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 180, 73, -1));

        jLabel4.setFont(new Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setText("  Topping");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 180, 73, -1));

        jLabel5.setFont(new Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setText("       Bill");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 312, 81, -1));

        jLabel6.setFont(new Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setText("     Staff");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 312, 73, -1));

        jLabel7.setFont(new Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.setText("  Account");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 312, 73, -1));

        jLabel8.setFont(new Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setText("   Statistic");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 460, 81, -1));

        jLabel9.setFont(new Font("Arial Black", 1, 12)); // NOI18N
        jLabel9.setText("   Log out");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 460, 73, -1));

        jLabel10.setIcon(new ImageIcon(getClass().getResource("/mycofffee2/BannerCoffee.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void jButton3ActionPerformed(ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton2ActionPerformed(ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagementMenu ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private JButton jButton1;
    private JButton jButton2;
    private JButton jButton3;
    private JButton jButton4;
    private JButton jButton5;
    private JButton jButton6;
    private JButton jButton7;
    private JButton jButton8;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    // End of variables declaration                   
}

